# Generated by Django 4.1.4 on 2022-12-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BenchmarkUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("is_admin", models.BooleanField(default=False)),
            ],
        ),
    ]
